### ISSUE TITLE
Change of Path in the Installation section 

### ISSUE THREAD

**Issue by kajal-puri** [dsvilarkovic/dynamic_plane_convolutional_onet#2]
Hi, 

Thank you for releasing the code. It has been very helpful while reading the paper to clarify the theory in the implementation. In the Installation section and Dataset sub-section, under the ShapeNet and Synthetic Room paragraphs, the following commands has been mentioned 

```
bash src/scripts/download_shape_net_data.sh
bash src/scripts/download_room_data.sh
```
While running this code, I found out that for this repository the files are located in the "scripts" and not "src/scripts" . So the commands that worked for me are 

```
bash scripts/download_shape_net_data.sh
bash scripts/download_room_data.sh
```

Please let me know if I'm missing something. Thanks!

**Comment by dsvilarkovic** [comment]
Hello, thank you for highlighting this issue.
I just updated README: https://github.com/dsvilarkovic/dynamic_plane_convolutional_onet/commit/253cae34c89404235c3a21d5d30710d9536c2363
