### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by kajal-puri** [dsvilarkovic/dynamic_plane_convolutional_onet#3]
Hi

I'm trying to reproduce the results of this repo. I have installed the conda environment along with dependencies, pretrained models and dataset correctly. I'm trying to perform the "Mesh Generation" step using pre-trained models. By using the following command
```
python generate.py configs/pointcloud/shapenet/shapenet_dynamic_3plane.yaml
```

I'm getting this Error. Can you help me solving it? System Information : I'm running this code on a Tesla T4 GPU.

```
<src.data.core.Shapes3dDataset object at 0x7f16ae654048>
Traceback (most recent call last):
  File "generate.py", line 45, in <module>
    checkpoint_io.load(cfg['test']['model_file'])
  File "/home/ubuntu/dynamic_plane_convolutional_onet/src/checkpoints.py", line 49, in load
    return self.load_file(filename)
  File "/home/ubuntu/dynamic_plane_convolutional_onet/src/checkpoints.py", line 68, in load_file
    raise FileExistsError
FileExistsError
Segmentation fault (core dumped)
```

**Comment by dsvilarkovic** [comment]
It seems it just didn't find a pretrained model_file, defined in line 53 on : https://github.com/dsvilarkovic/dynamic_plane_convolutional_onet/blob/main/configs/pointcloud/shapenet/shapenet_dynamic_3plane.yaml

Try specifying absolute path there instead of just 'model_best.pt'

To extend this further: 'model_best.pt' is just a copy pasted filename for every test.model_file in configs/pointcloud/shapenet folder, and downloaded files in the [polybox link](https://polybox.ethz.ch/index.php/s/ehK175BH7oVYnxy) have full names not adapted to that lame filename. When I have time I will test out all configurations for respective filenames.

**Comment by kajal-puri** [comment]
Thanks for suggesting the fix. I replaced the *mode_best.pt* file with the absolute path of pre-trained model file */home/ubuntu/dynamic_plane_convolutional_onet/shapenet/shapenet_dynamic_3plane.pt* and got the following error.

```
<src.data.core.Shapes3dDataset object at 0x7fa0a2376358>
/home/ubuntu/dynamic_plane_convolutional_onet/shapenet/shapenet_dynamic_3plane.pt
=> Loading checkpoint from local file...
Warning: generator does not support pointcloud generation.
  0%|                                                  | 0/8751 [00:00<?, ?it/s]THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/THC/generic/THCTensorScatterGather.cu line=71 error=98 : invalid device function

Traceback (most recent call last):
  File "generate.py", line 143, in <module>
    out = generator.generate_mesh(data)
  File "/home/ubuntu/dynamic_plane_convolutional_onet/src/dynamic_planes_conv_onet/generation.py", line 76, in generate_mesh
    c = self.model.encode_inputs(inputs)
  File "/home/ubuntu/dynamic_plane_convolutional_onet/src/dynamic_planes_conv_onet/models/__init__.py", line 95, in encode_inputs
    c = self.encoder(inputs)
  File "/home/ubuntu/miniconda3/envs/dyn_conv_onet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/dynamic_plane_convolutional_onet/src/encoder/pointnet.py", line 294, in forward
    pooled = self.pool_local(coord, index, net)
  File "/home/ubuntu/dynamic_plane_convolutional_onet/src/encoder/pointnet.py", line 253, in pool_local
    fea = fea.gather(dim=2, index=index[key].expand(-1, fea_dim, -1))
RuntimeError: cuda runtime error (98) : invalid device function at /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/THC/generic/THCTensorScatterGather.cu:71
```

**Comment by splionar** [comment]
Hi @kajal-puri, unfortunately I cannot reproduce your error. The issue might be from your GPU/CUDA setup. Probably check your nvcc version or reinstalling the conda environment.
