### ISSUE TITLE
What is the resolution of surface reconstruction?

### ISSUE THREAD

**Issue by mengbo123** [dsvilarkovic/dynamic_plane_convolutional_onet#4]
How much resolution is used to reconstruction the synthetic rooms dataset in your article? 128^3 or 256^3?

**Comment by dsvilarkovic** [comment]
Should be 128^3, what makes you think it's 256^3? Curious

**Comment by mengbo123** [comment]
> Should be 128^3, what makes you think it's 256^3? Curious

I also think it 's 128^3. Thank you

**Comment by dsvilarkovic** [comment]
K, i'll close this one. None of our config files and paper mention the 256 resolution, only 128.
